import torch
from torch import Tensor
from typing import Callable, Tuple

def probability_flow_ode_integrator(
    x_0,
    t_0,
    t_end,
    n_steps,
    ode_drift_coefficient,
):
    """
    Integrate the Probability Flow ODE on a regular time grid.

    This function generates synthetic samples by numerically solving the
    deterministic Probability Flow ODE associated with a score-based diffusion
    model. Unlike the reverse SDE sampler, this integrator does not inject
    noise during sampling.

    The ODE has the form

        dx/dt = f(x,t) - 0.5 * g(t)^2 * s_theta(x,t),

    where f(x,t) is the drift of the forward process, g(t) is the diffusion
    coefficient, and s_theta(x,t) is the learned score function.

    Args:
        x_0: Initial images of shape
            (batch_size, n_channels, image_height, image_width).
            These are typically sampled from the prior distribution at time t_0.
        t_0: Initial time of the integration interval.
        t_end: Final time of the integration interval.
        n_steps: Number of integration steps.
        ode_drift_coefficient: Function of (x_t, t) that returns the drift
            term of the Probability Flow ODE for a batch of images.

    Returns:
        times: 1D tensor containing the integration time grid of length
            n_steps + 1.
        x_t: Tensor containing the full trajectories generated by the ODE
            solver. Its shape is
            (batch_size, n_channels, image_height, image_width, n_steps + 1).

    Notes:
        - The integration is performed with an explicit Euler scheme.
        - The method is deterministic: no Gaussian noise is added.
        - If t_0 > t_end, the integration proceeds backward in time.

    Example:
        >>> ode_drift = model.get_probability_flow_drift(score_model)
        >>> times, x_t = probability_flow_ode_integrator(
        ...     x_0=image_T,
        ...     t_0=1.0,
        ...     t_end=1.0e-3,
        ...     n_steps=500,
        ...     ode_drift_coefficient=ode_drift,
        ... )
    """
    device = x_0.device
    times = torch.linspace(t_0, t_end, n_steps + 1, device=device)
    dt = times[1] - times[0]

    x_t = torch.empty((*x_0.shape, n_steps + 1), device=device)
    x_t[..., 0] = x_0
    x = x_0

    for n in range(n_steps):
        t = torch.full((x.shape[0],), times[n], device=device, dtype=x.dtype)
        drift = ode_drift_coefficient(x, t)
        x = x + drift * dt
        x_t[..., n + 1] = x

    return times, x_t